baseURL = 'https://makerspace.olaru.dk/'
publishDir = 'docs'
languageCode = 'en-us'
title = "O'Town Makerspace"
theme = 'hugo-up-business-main'

[params]
  description = "Empowering communities through volunteer action"
  copyright = "Â© 2026 O'Town Makerspace. All rights reserved."
  logo = "images/branding/otown_logo_2.svg"
  location = ["Copenhagen, Denmark"]
  contact = ["info@theotowngarage.com"]
  calendarIcsUrl = "https://calendar.google.com/calendar/ical/info%40theotowngarage.com/public/basic.ics"
  docSections = ["Getting Started", "General Rules", "Resources", "Legal & Policy"]

  [params.colors]
    accent = "#F68048"
    accent_2 = "#e75008"
    primary = "#EDF2F8"
    primary_2 = "#E1E9F4"
    secondary = "#0D1A63"
    secondary_2 = "#1A2CA3"
    gray_light = "#EEF1FF"
    gray_dark = "#0D1A63"
    tertiary = "#1A2CA3"

  [params.social]
    facebook = "#"
    instagram = "#"

# Enable raw HTML in markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

# Main navigation menu
[[menus.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menus.main]]
  name = "Events"
  url = "/events/"
  weight = 3

[[menus.main]]
  name = "Workshops"
  url = "/about/work-areas/"
  weight = 4

[[menus.main]]
  name = "Docs"
  url = "/docs/"
  weight = 5

[[menus.main]]
  name = "News"
  url = "/news/"
  weight = 6

# CTA button in header
[[menus.buttons]]
  name = "Join Us"
  url = "/#join"
  weight = 1

# Footer menu
[[menus.footer]]
  name = "About"
  url = "/about/"
  weight = 1

[[menus.footer]]
  name = "Events"
  url = "/events/"
  weight = 2

[[menus.footer]]
  name = "Documentation"
  url = "/docs/"
  weight = 3

[[menus.footer]]
  name = "News"
  url = "/news/"
  weight = 4
