baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "O'Town Makerspace"
theme = 'hugo-up-business-main'

[params]
  description = "Empowering communities through volunteer action"
  copyright = "Â© 2026 O'Town Makerspace. All rights reserved."
  logo = "images/branding/otown_logo_2.svg"

  [params.social]
    facebook = "#"
    instagram = "#"

  location = [
    "Copenhagen, Denmark"
  ]

  contact = [
    "info@theotowngarage.com"
  ]

# Enable raw HTML in markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Main navigation menu
[[menus.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menus.main]]
  name = "Events"
  url = "/events/"
  weight = 3

[[menus.main]]
  name = "Docs"
  url = "/docs/"
  weight = 4

[[menus.main]]
  name = "News"
  url = "/news/"
  weight = 5

# CTA button in header
[[menus.buttons]]
  name = "Join Us"
  url = "/#join"
  weight = 1

# Footer menu
[[menus.footer]]
  name = "About"
  url = "/about/"
  weight = 1

[[menus.footer]]
  name = "Events"
  url = "/events/"
  weight = 2

[[menus.footer]]
  name = "Documentation"
  url = "/docs/"
  weight = 3

[[menus.footer]]
  name = "News"
  url = "/news/"
  weight = 4
