baseURL = 'https://makerspace.olaru.dk/'
publishDir = 'docs'
title = "O'Town Makerspace"
theme = 'hugo-up-business-main'
defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageCode = 'en-us'
    languageName = 'English'
    weight = 1

  [languages.da]
    languageCode = 'da'
    languageName = 'Dansk'
    weight = 2

[params]
  description = "Empowering makers to bring ideas to life"
  copyright = "© 2026 O'Town Makerspace. All rights reserved."
  logo = "images/branding/otown_logo_2.svg"
  location = ["Havnegade 57, 5000 Odense C, Denmark"]
  contact = ["info@theotowngarage.com"]
  calendarIcsUrl = "https://calendar.google.com/calendar/ical/info%40theotowngarage.com/public/basic.ics"
  ogImage = "images/og-default.jpg"

  [params.colors]
    accent = "#F68048"
    accent_2 = "#e75008"
    primary = "#EDF2F8"
    primary_2 = "#E1E9F4"
    secondary = "#0D1A63"
    secondary_2 = "#1A2CA3"
    gray_light = "#EEF1FF"
    gray_dark = "#0D1A63"
    tertiary = "#1A2CA3"

  [params.social]
    facebook = "#"
    instagram = "#"
    discord = "https://discord.gg/HDR8jsUp"

# Enable raw HTML in markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

# ── English menus ──

[[languages.en.menus.main]]
  name = "Home"
  url = "/"
  weight = 1

[[languages.en.menus.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[languages.en.menus.main]]
  name = "Events"
  url = "/events/"
  weight = 3

[[languages.en.menus.main]]
  name = "Info"
  url = "#"
  weight = 4

[[languages.en.menus.main]]
  name = "Gallery"
  url = "/gallery/"
  weight = 5

[[languages.en.menus.main]]
  name = "Articles"
  url = "/articles/"
  weight = 6

[[languages.en.menus.main]]
  name = "News"
  url = "/news/"
  weight = 7

[[languages.en.menus.buttons]]
  name = "Join Us"
  url = "/#join"
  weight = 1

[[languages.en.menus.footer]]
  name = "About"
  url = "/about/"
  weight = 1

[[languages.en.menus.footer]]
  name = "Events"
  url = "/events/"
  weight = 2

[[languages.en.menus.footer]]
  name = "Getting Started"
  url = "/getting-started/"
  weight = 3

[[languages.en.menus.footer]]
  name = "Documentation"
  url = "/docs/"
  weight = 4

[[languages.en.menus.footer]]
  name = "Gallery"
  url = "/gallery/"
  weight = 5

[[languages.en.menus.footer]]
  name = "Articles"
  url = "/articles/"
  weight = 6

[[languages.en.menus.footer]]
  name = "News"
  url = "/news/"
  weight = 7

# ── Danish menus ──

[[languages.da.menus.main]]
  name = "Hjem"
  url = "/"
  weight = 1

[[languages.da.menus.main]]
  name = "Om os"
  url = "/about/"
  weight = 2

[[languages.da.menus.main]]
  name = "Arrangementer"
  url = "/events/"
  weight = 3

[[languages.da.menus.main]]
  name = "Info"
  url = "#"
  weight = 4

[[languages.da.menus.main]]
  name = "Galleri"
  url = "/gallery/"
  weight = 5

[[languages.da.menus.main]]
  name = "Artikler"
  url = "/articles/"
  weight = 6

[[languages.da.menus.main]]
  name = "Nyheder"
  url = "/news/"
  weight = 7

[[languages.da.menus.buttons]]
  name = "Bliv medlem"
  url = "/#join"
  weight = 1

[[languages.da.menus.footer]]
  name = "Om os"
  url = "/about/"
  weight = 1

[[languages.da.menus.footer]]
  name = "Arrangementer"
  url = "/events/"
  weight = 2

[[languages.da.menus.footer]]
  name = "Kom i gang"
  url = "/getting-started/"
  weight = 3

[[languages.da.menus.footer]]
  name = "Dokumentation"
  url = "/docs/"
  weight = 4

[[languages.da.menus.footer]]
  name = "Galleri"
  url = "/gallery/"
  weight = 5

[[languages.da.menus.footer]]
  name = "Artikler"
  url = "/articles/"
  weight = 6

[[languages.da.menus.footer]]
  name = "Nyheder"
  url = "/news/"
  weight = 7
